### ISSUE TITLE
foam_getCellPoints returns wrong points

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-openfoam#13]
see `std::vector<int> foam_getCellPoints(std::string name, int label)`

**Comment by khiltunen** [comment]
Did you find something on that ?

**Comment by nathanfranklin** [comment]
I haven't found a fix or what is going on. I have tried different things but no luck so far.

  It currently doesn't work.

**Comment by khiltunen** [comment]
I think that the reason is that the Mesh iter_cells() do not keep the ordering. We must obey the ordering which cellShape wants (i think we decided this that SimPhoNy mesh will obey that ordering) to be able to use in addMesh cellShape object. Now it seems that the ordering is lost.

**Comment by khiltunen** [comment]
I have also tested the interface outside SimPhoNy framework and it seems to work (at least with hex cells) using the original implementation.

**Comment by khiltunen** [comment]
Looked ta mesh.py and self._cells type is ordinary dictionary not OrderedDict.

**Comment by nathanfranklin** [comment]
> I have also tested the interface outside SimPhoNy framework and it seems to work (at least with hex cells) using the original implementation.

You are right.  It didn't work cause I had a mistake in my test (https://github.com/simphony/simphony-openfoam/blob/feature-openfoammesh-numerola-fix-cell/foam_controlwrapper/tests/test_controlwrapper.py#L100).  Then I begin to debug my changed implementation of `foam_getCellPoints` which never needed to be changed.   Wasted almost a day on that :(

**Comment by nathanfranklin** [comment]
hmm..wait one second. i think this still might be a bug.  will use a new branch to illustrate the problem

**Comment by nathanfranklin** [comment]
see #14

> I think that the reason is that the Mesh iter_cells() do not keep the ordering. We must obey the ordering which cellShape wants (i think we decided this that SimPhoNy mesh will obey that ordering) to be able to use in addMesh cellShape object. Now it seems that the ordering is lost.

I dont think this is the reason.  Because this fails for just 1 cell (so `iter_cells` doesnt play role).

cellShape is given the correct order of points.  cell.points is a list and is in the correct order.

**Comment by khiltunen** [comment]
I did meaned to write iter_points(). But points does not have to be inborder if we have label uid mapping and cell.points order is kept

**Comment by nathanfranklin** [comment]
right

so #14 is a bug, right? as cell.points order is correct

**Comment by nathanfranklin** [comment]
I have checked the hex `cellShape` in foam_addMesh and it has the correct order of points.  After creating this new mesh ( at https://github.com/simphony/simphony-openfoam/blob/feature-openfoammesh-numerola/openfoam-interface/simphonyInterface.C#L636) then if you ask for the cell's shape `cellSphape`, it has the wrong order of points.

I have been trying different things in `foam_getCellPoints` to no avail: seeing if i can get the right order of points when iterating over the faces of the  shape (`cellShape`) or iterating over the cell's faces. (inspired by `In a cell, you loop through faces in order and grab them as they come, skipping the duplicates` in http://www.cfd-online.com/Forums/openfoam-meshing-technical/61657-point-labels-associated-cell.html

**Comment by nathanfranklin** [comment]
@khiltunen  did you write `foam_getCellPoints` and `order_cellPoints`.  if not, can you point me to where they are from.

**Comment by nathanfranklin** [comment]
@khiltunen  i think we need to set up a testing of `simphonyInterface.C` (or alternatively `openfoam-interface`).

we would a test(s) which uses uses the following method:
```
void foam_addMesh(std::string name,std::vector<double> points,  std::vector<int> cellpoints, std::vector<int> facepoints, std::vector<std::string> patchnames, std::vector<int> patchfaces)
```
and then tests the results of:

```
std::vector<int> foam_getCellPoints(std::string name, int label)
```

I will have time to look at this issue or other openFoam-wrapper issues on Monday but then the rest of the week I am not able to devote much time.

**Comment by khiltunen** [comment]
Those are written by my self. I think that this procedure will not return the same ordering of points but it will return ordering which match cellShape ordering. Namely you can start the node ordering from every node and then add points from every face the point belongs to and after that the nodes from opposite side face. I think that if the global node ordering is not changed then it might return also local ordering the same. So i think that we cant have generally the ordering fixed. Ordering must only fullfill cellShape requirements

**Comment by nathanfranklin** [comment]
> think that if the global node ordering is not changed then it might return also local ordering the same.

does the global node ordering change?

> Ordering must only fulfill cellShape requirements

I think I understand that and see for `cell.points` for FoamMesh supports only what can be described by  open foam 'cellShapes' ( .e.g. `(hex 8(0 1 2 3 4 5 6 7))`from http://www.openfoam.org/docs/user/mesh-description.php ).

I see in the test (https://github.com/simphony/simphony-openfoam/blob/feature-openfoammesh-numerola/foam_controlwrapper/tests/test_controlwrapper.py#L49) you used the correct order of the points for the cell (coresponding to the 'hex' 'cellShape').

so we would expect the results of get_cell (https://github.com/simphony/simphony-openfoam/blob/feature-openfoammesh-numerola/foam_controlwrapper/foam_mesh.py#L283-L285)`) to have the correct order of points for the input cell.   Which it doesn't according to the testing (see #14) 

I feel like this is a *bug* but want to double check that you also think its a bug.

**Comment by khiltunen** [comment]
I think that when mesh is converted to OpenFoam's internal format using cellShape there is no mechanism to recover the original ordering of nodes in cell without having the original cellShape ordering information. We can get ordering which fullfills cellShape ordering, but it always depend on what node and face of the cell is choosed to start the noce ordering. See attached image
![of cellshape and ordering](https://cloud.githubusercontent.com/assets/8565707/6776335/f47a223a-d145-11e4-8ad3-ed60b496adea.png)
