### ISSUE TITLE
tests fail when reading simplemesh.cuds

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-openfoam#26]
@TobiasRasp and I noticed a problem when running the tests on simphony-openfoam.  See below for details  We were using a recent version of simphony-common which caused a problem when running the simphony-openfoam tests as the file used for testing ``foam_controlwrapper/tests/simplemesh.cuds`` is in an older format.

I would suggest what was also suggested in #25 that if it is possible, it would be best not to use the file when testing (but to instead "create the CUDS containers components at runtime").  

---------------------------------------

simphony-common  - 0.1.4.dev0  (#bb0e43f9250b3c07421743ad0993c783b041d253)
simphony-openfoam  - 0.1.2.dev0 (13e2f4898ab84c29b1dba19a68dcf31ea4e5ba80)

```
Traceback (most recent call last):
   File "foam_controlwrapper/tests/test_controlwrapper.py", line 305, in
test_parallel_run
     mesh_inside_wrapper = wrapper.add_mesh(mesh_from_file)
   File "foam_controlwrapper/foam_controlwrapper.py", line 132, in add_mesh
     self._meshes[mesh.name] = FoamMesh(mesh.name, mesh)
   File "foam_controlwrapper/foam_mesh.py", line 75, in __init__
     for point in mesh.iter_points():
   File
"/W5/ras/SimPhoNy/wrapperTest/simphony-common/simphony/io/h5_mesh.py",
line 618, in iter_points
     self._uidData[uuid.UUID(hex=row['data'], version=4)]
   File
"/W5/ras/SimPhoNy/wrapperTest/simphony-common/simphony/io/data_container_table.py",
line 100, in __getitem__
     'Record (id={id}) does not exist'.format(id=uid))
KeyError: 'Record (id=fbb14704-3cd3-4bab-83c2-9ffdd3fb2558) does not exist'

```

**Comment by khiltunen** [comment]
This is a common problem with cuds files. I can make adjustments to generate it on runtime.This needs to include corresponding foam mesh files to package.

**Comment by ahashibon** [comment]
adding the mesh file from openfoam and converting should be a good intermediate solution. Once we have ncadfluid and the boundary (geometry) is supported in CUDS, we can generate the mesh from scratch. We should add this to the to-do list once the specifications are finalized in the SSB.

**Comment by nathanfranklin** [comment]
> adding the mesh file from openfoam and converting should be a good intermediate solution. Once we have ncadfluid and the boundary (geometry) is supported in CUDS, we can generate the mesh from scratch. We should add this to the to-do list once the specifications are finalized in the SSB.
adding the mesh file from openfoam and converting should be a good intermediate solution. 

sounds good for ``foam_controlwrapper/examples/poiseuille/poiseuille.cuds`` where i imagine the mesh is complicated.  Is  the mesh in ``foam_controlwrapper/tests/simplemesh.cuds`` simple enough that it can be generated dynamically (i.e. create a stand-alone mesh and then add the required points, cells, etc.)?

**Comment by khiltunen** [comment]
I suppose that foam needs at least two cells to get solution changed after two consequent solving step. Then the mesh can be quite easily constructed with corresponding boundaries in the tests.
