### ISSUE TITLE
foam_mesh_to_h5cuds.py fails 

### ISSUE THREAD

**Issue by TobiasRasp** [simphony/simphony-openfoam#30]
when running the comand:

``` 
python foam_mesh_to_h5cuds.py

```
from the examples section of the OpenFoam-wrapper (simphony-openfoam version 0.1.2dev0 (13e2f4898ab84c29b1dba19a68dcf31ea4e5ba80)) the following error message appears:

```
Traceback (most recent call last):
  File "foam_mesh_to_h5cuds.py", line 11, in <module>
    mesh_inside_wrapper = foam_controlwrapper.read_foammesh(name, path)
TypeError: read_foammesh() takes exactly 2 arguments (3 given)
```

The problem can be solved by changing the method definition 
```
   def read_foammesh(name, path):

```
to
```
    @classmethod
    def read_foammesh(cls, name, path):
```
in foam_controlwrapper.py

**Comment by khiltunen** [comment]
read_foammesh was earlier classmethod, but it was changed. It is better to change the foam_mesh_to_h5cuds.py so that the method is imported from module. I'll make a new branch for bug fix
