### ISSUE TITLE
engine's run method is different that abcmodelingengine

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-openfoam#35]
the FILE-IO and INTERNAL wrappers's run method is incorrectly returning something

**Comment by jmarcelogimenez** [comment]
Solved in branch fix-issues-july2015, modified in both internal and io wrappers.

**Comment by nathanfranklin** [comment]
> Solved in branch fix-issues-july2015, modified in both internal and io wrappers.

I would suggest splitting up fix-issues-july2015 into separate branches.  it would be easier to review  the separate PRs.   For example, it would be easy to review the PR for this work and not let get delayed by any issues in the other PRs.
