### ISSUE TITLE
duplicate foam_mesh.py

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-openfoam#37]
There two foam_mesh.py in the same subpackage 

https://github.com/simphony/simphony-openfoam/blob/master/foam_internalwrapper/tests/foam_mesh.py

and

https://github.com/simphony/simphony-openfoam/blob/master/foam_internalwrapper/foam_mesh.py

It looks that the one inside the tests folder is a copy and should probably be removed

**Comment by jmarcelogimenez** [comment]
Solved in fix-issues-july2015
