### ISSUE TITLE
Alphabetic sorting of time directories

### ISSUE THREAD

**Issue by TobiasRasp** [simphony/simphony-openfoam#44]
The method get_last_time (foam_runner.py) contains a alphabetic sorting of a list of existing time 
directories: 
time_dirs.sort()

This leads to errors when having for example the directories [500, 1000, 1500, 2000]. After alphabetic sorting this becomes [1000,1500,2000,500].

Correct numeric sorting can be done e.g. by
time_dirs.sort(key=lambda time_dirs: int(time_dirs.split()[0]))

**Comment by khiltunen** [comment]
I'll pick this up now
