### ISSUE TITLE
Use latest version of simphony-common (>=0.2.0)

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-openfoam#51]

**Comment by nathanfranklin** [comment]
I have seen the work on https://github.com/simphony/simphony-openfoam/tree/use-common-0.2.  Any updates on that?

**Comment by khiltunen** [comment]
Juan has now fixed the issue on updating values at once on internal wrapper and we can make PR on this. I just have to do some modifications to unit tests.

**Comment by nathanfranklin** [comment]
Thanks for the update!

**Comment by khiltunen** [comment]
fixed in v 1.5.0
