### ISSUE TITLE
There no implementation of a CUDS mesh container for this wrapper

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-openfoam#8]
It is not possible to add, get and remove a mesh cuds in the openfoam wrapper.

https://github.com/simphony/simphony-openfoam/blob/master/foam_controlwrapper/foam_controlwrapper.py#L196

**Comment by itziakos** [comment]
Please note that this is a blocking issue for the integration

**Comment by khiltunen** [comment]
Added codes to watch to
https://github.com/simphony/simphony-openfoam/tree/feature-openfoammesh-numerola
There is still some open issues. One concerning the boundary patches move to foam mesh. I'm working on that and hope to get working ASAP.  Found that on tests. Another one is concerning uuids on FileMesh cell.points and face.points. I'll report that to  @roigcarlo.

@nathanfranklin
@ahashibon

**Comment by nathanfranklin** [comment]
@khiltunen   have I been assigned to this issue for review?  or  further implementation?

**Comment by khiltunen** [comment]
I would appreciate if you could give help also on implementation, but i think if we can overcome those two issues i mentioned, the integration can go further. In the future the main point is to make operations more efficient and also extend to other solvers (only simpleFoam handled at a moment). Every comment on code design are welcome.

**Comment by khiltunen** [comment]
The boundary treatment issue is now corrected. To get tests pass we need to have the FileMesh cell.nodes, face.nodes, edge.nodes uid issue solved. Carlos is fixing that @roigcarlo.
@itziakos could you also help me on interface library setup. It seems to work otherwise, but the compiled OpenFoam's interface library is not in the path. It will put that to standard OF's user directory, but its seems that at least travis is not allowing that.

**Comment by nathanfranklin** [comment]
> I would appreciate if you could give help also on implementation

@khiltunen  i can begin looking at it this afternoon.

**Comment by itziakos** [comment]
2015-03-12 7:45 GMT+00:00 khiltunen <notifications@github.com>:

> The boundary treatment issue is now corrected. To get tests pass we need
> to have the FileMesh cell.nodes, face.nodes, edge.nodes uid issue solved.
> Carlos is fixing that @roigcarlo <https://github.com/roigcarlo>.
> @itziakos <https://github.com/itziakos> could you also help me on
> interface library setup. It seems to work otherwise, but the compiled
> OpenFoam's interface library is not in the path. It will put that to
> standard OF's user directory, but its seems that at least travis is not
> allowing that.
>

I have fixed the travis-ci built. The issue is that travis-ci is using
virtualenv to create a separate python environment where python packages
can be installed without the need of sudo. The virtual-env was created with
access to the install python packages, however that setup does not always
work  extension packages like openfoam-interface (I think it has to do with
the two step build but I am not sure). Anyway, the build now runs the tests
correctly.

Virtualenv info -- https://virtualenv.pypa.io/en/latest/userguide.html

Ioannis

**Comment by khiltunen** [comment]
I've made some changes to overcome the uuid problem on FileMesh and i think this is now ready to merge. Let me know if there is something to change before merging at this point.
@nathanfranklin 
@itziakos 
@ahashibon

**Comment by itziakos** [comment]
@khiltunen, can you create a pr so that we can make our comments?

**Comment by nathanfranklin** [comment]
@khiltunen , I started to take a look at the code this afternoon and made some initial comments on the PR. I will look more in detail tomorrow.

**Comment by itziakos** [comment]
> The boundary treatment issue is now corrected. To get tests pass we need to have the FileMesh cell.nodes, face.nodes, edge.nodes uid issue solved. 

@khiltunen, Why not use the `Mesh` object for the tests?

**Comment by khiltunen** [comment]
Unittests pass and Mesh object is used there, but in example codes FileMesh is used.

**Comment by itziakos** [comment]
@khiltunen, not all of the operations are currently supported correct?

Can you create an github issue (or issues) on what is currently not supported from the Mesh CUDS container API.
